import type { Metadata } from "next";
import {
  Space_Grotesk as SpaceGrotesk,
  Source_Code_Pro as codePro,
  Sora,
} from "next/font/google";
import "./globals.css";

const spaceGrotesk = SpaceGrotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const sourceCodePro = codePro({
  variable: "--font-code",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Brainwave",
  description: "Generated by create next app",
  icons: {
    icon: "/brainwave-symbol.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} ${sora.variable}  ${sourceCodePro.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
